// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deactivation_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDeactivationToken = `-- name: CreateDeactivationToken :exec
INSERT INTO deactivation_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateDeactivationTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateDeactivationToken(ctx context.Context, arg CreateDeactivationTokenParams) error {
	_, err := q.db.ExecContext(ctx, createDeactivationToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const getDeactivationToken = `-- name: GetDeactivationToken :one
SELECT user_id, expires_at FROM deactivation_tokens
WHERE token = $1
`

type GetDeactivationTokenRow struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) GetDeactivationToken(ctx context.Context, token string) (GetDeactivationTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getDeactivationToken, token)
	var i GetDeactivationTokenRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const deleteDeactivationToken = `-- name: DeleteDeactivationToken :exec
DELETE FROM deactivation_tokens
WHERE token = $1
`

func (q *Queries) DeleteDeactivationToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteDeactivationToken, token)
	return err
}
