// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCategory = `-- name: AddCategory :exec
UPDATE ingredients
SET category = $1
WHERE name = $2
`

type AddCategoryParams struct {
	Category string
	Name     string
}

func (q *Queries) AddCategory(ctx context.Context, arg AddCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addCategory, arg.Category, arg.Name)
	return err
}

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (id, name, image_key, created_at, updated_at)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	NOW(),
	NOW()
) RETURNING id, name, image_key, created_at, updated_at, category
`

type CreateIngredientParams struct {
	Name     string
	ImageKey string
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient, arg.Name, arg.ImageKey)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :many
SELECT id, name, image_key, created_at, updated_at, category FROM ingredients
WHERE category = $1
`

func (q *Queries) GetCategory(ctx context.Context, category string) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, getCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngredientFromName = `-- name: GetIngredientFromName :one
SELECT id FROM ingredients
WHERE name = $1
`

func (q *Queries) GetIngredientFromName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getIngredientFromName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getIngredientName = `-- name: GetIngredientName :one
SELECT name FROM ingredients
WHERE id = $1
`

func (q *Queries) GetIngredientName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getIngredientName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getIngredients = `-- name: GetIngredients :many
SELECT id, name FROM ingredients
`

type GetIngredientsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetIngredients(ctx context.Context) ([]GetIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientsRow
	for rows.Next() {
		var i GetIngredientsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
