// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO messages (id, user_email, message)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
`

type AddMessageParams struct {
	UserEmail string
	Message   string
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.ExecContext(ctx, addMessage, arg.UserEmail, arg.Message)
	return err
}

const getAllMessages = `-- name: GetAllMessages :many
SELECT id, user_email, message, resolved, status FROM messages
WHERE status != 'archived'
`

func (q *Queries) GetAllMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getAllMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Message,
			&i.Resolved,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageById = `-- name: GetMessageById :one
SELECT id, user_email, message, resolved, status FROM messages 
WHERE id = $1
`

func (q *Queries) GetMessageById(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageById, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Message,
		&i.Resolved,
		&i.Status,
	)
	return i, err
}

const getMessagesWithTag = `-- name: GetMessagesWithTag :many
SELECT id, user_email, message, resolved, status FROM messages 
WHERE status = $1
`

func (q *Queries) GetMessagesWithTag(ctx context.Context, status string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesWithTag, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Message,
			&i.Resolved,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMessageStatus = `-- name: SetMessageStatus :exec
UPDATE messages
SET status = $1
WHERE id = $2
`

type SetMessageStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetMessageStatus(ctx context.Context, arg SetMessageStatusParams) error {
	_, err := q.db.ExecContext(ctx, setMessageStatus, arg.Status, arg.ID)
	return err
}
