// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Conversion struct {
	IngredientID uuid.UUID
	FromUnit     string
	ToUnit       string
	Ratio        float32
}

type Ingredient struct {
	ID        uuid.UUID
	Name      string
	ImageKey  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type IngredientRetailUnit struct {
	IngredientID uuid.UUID
	RetailUnit   string
}

type Recipe struct {
	ID           uuid.UUID
	Title        string
	Author       string
	Description  string
	Instructions string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
}

type RecipeIngredient struct {
	RecipeID     uuid.UUID
	IngredientID uuid.UUID
	Quantity     float32
	Unit         string
}

type RefreshToken struct {
	ID        string
	CreatedAt time.Time
	RevokedAt sql.NullTime
	ExpiresAt time.Time
	UserID    uuid.UUID
}

type RetailConversion struct {
	UniversalUnit string
	RetailUnit    string
	Ratio         float32
}

type RetailUnit struct {
	Name string
}

type ShoppingList struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type ShoppingListRecipe struct {
	ShoppingListID uuid.UUID
	RecipeID       uuid.UUID
	Quantity       int32
}

type Unit struct {
	Name         string
	Abbreviation string
}

type UniversalUnit struct {
	Name string
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	HashedPw  string
	Admin     bool
	ImageKey  string
}
