// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_likes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getLikes = `-- name: GetLikes :one
SELECT COUNT(*) FROM recipe_likes
WHERE recipe_id = $1
`

func (q *Queries) GetLikes(ctx context.Context, recipeID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLikes, recipeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const likeRecipe = `-- name: LikeRecipe :exec
INSERT INTO recipe_likes (user_id, recipe_id)
VALUES (
  $1,
  $2
)
`

type LikeRecipeParams struct {
	UserID   uuid.UUID
	RecipeID uuid.UUID
}

func (q *Queries) LikeRecipe(ctx context.Context, arg LikeRecipeParams) error {
	_, err := q.db.ExecContext(ctx, likeRecipe, arg.UserID, arg.RecipeID)
	return err
}

const unlikeRecipe = `-- name: UnlikeRecipe :exec
DELETE FROM recipe_likes
WHERE (user_id, recipe_id) = ($1, $2)
`

type UnlikeRecipeParams struct {
	UserID   uuid.UUID
	UserID_2 uuid.UUID
}

func (q *Queries) UnlikeRecipe(ctx context.Context, arg UnlikeRecipeParams) error {
	_, err := q.db.ExecContext(ctx, unlikeRecipe, arg.UserID, arg.UserID_2)
	return err
}
