// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipeIngredients.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addToRecipe = `-- name: AddToRecipe :one
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit)
VALUES (
	$1,
	$2,
	$3,
	$4
) RETURNING recipe_id, ingredient_id, quantity, unit
`

type AddToRecipeParams struct {
	RecipeID     uuid.UUID
	IngredientID uuid.UUID
	Quantity     float32
	Unit         string
}

func (q *Queries) AddToRecipe(ctx context.Context, arg AddToRecipeParams) (RecipeIngredient, error) {
	row := q.db.QueryRowContext(ctx, addToRecipe,
		arg.RecipeID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.RecipeID,
		&i.IngredientID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}

const clearFromRecipe = `-- name: ClearFromRecipe :exec
DELETE FROM recipe_ingredients 
WHERE recipe_id = $1
`

func (q *Queries) ClearFromRecipe(ctx context.Context, recipeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearFromRecipe, recipeID)
	return err
}

const getIngredientList = `-- name: GetIngredientList :many
SELECT ingredients.name, recipe_ingredients.recipe_id, recipe_ingredients.ingredient_id, recipe_ingredients.quantity, recipe_ingredients.unit FROM ingredients
INNER JOIN recipe_ingredients ON ingredients.id = recipe_ingredients.ingredient_id
WHERE recipe_ingredients.recipe_id = $1
`

type GetIngredientListRow struct {
	Name         string
	RecipeID     uuid.UUID
	IngredientID uuid.UUID
	Quantity     float32
	Unit         string
}

func (q *Queries) GetIngredientList(ctx context.Context, recipeID uuid.UUID) ([]GetIngredientListRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngredientList, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientListRow
	for rows.Next() {
		var i GetIngredientListRow
		if err := rows.Scan(
			&i.Name,
			&i.RecipeID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
