// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkIfSeeded = `-- name: CheckIfSeeded :one
SELECT id FROM recipes
WHERE description = $1
`

func (q *Queries) CheckIfSeeded(ctx context.Context, description string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, checkIfSeeded, description)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (id, title, author, created_at, updated_at, user_id, description, image_key, instructions)
VALUES(
	gen_random_uuid(),
	$1,
	$2,
	NOW(),
	NOW(),
	$3,
	$4,
	$5,
	$6
)
RETURNING id
`

type CreateRecipeParams struct {
	Title        string
	Author       string
	UserID       uuid.UUID
	Description  string
	ImageKey     string
	Instructions string
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.Title,
		arg.Author,
		arg.UserID,
		arg.Description,
		arg.ImageKey,
		arg.Instructions,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, id)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT recipes.id, recipes.title, recipes.author, recipes.description, recipes.instructions, recipes.image_key, recipes.created_at, recipes.updated_at, recipes.user_id, COUNT(recipe_likes.user_id) AS likes FROM recipes
INNER JOIN recipe_likes ON recipe_likes.recipe_id = recipes.id
WHERE id = $1
GROUP BY recipes.id
`

type GetRecipeRow struct {
	ID           uuid.UUID
	Title        string
	Author       string
	Description  string
	Instructions string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	Likes        int64
}

func (q *Queries) GetRecipe(ctx context.Context, id uuid.UUID) (GetRecipeRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i GetRecipeRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Instructions,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Likes,
	)
	return i, err
}

const getRecipeImageKey = `-- name: GetRecipeImageKey :one
SELECT image_key FROM recipes
WHERE id = $1
`

func (q *Queries) GetRecipeImageKey(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getRecipeImageKey, id)
	var image_key string
	err := row.Scan(&image_key)
	return image_key, err
}

const getRecipeList = `-- name: GetRecipeList :many
SELECT recipes.id, recipes.title, recipes.author, recipes.description, recipes.instructions, recipes.image_key, recipes.created_at, recipes.updated_at, recipes.user_id, COUNT(recipe_likes.user_id) AS likes FROM recipes
LEFT JOIN recipe_likes ON recipe_likes.recipe_id = recipes.id
GROUP BY recipes.id
ORDER BY likes DESC
LIMIT 10
`

type GetRecipeListRow struct {
	ID           uuid.UUID
	Title        string
	Author       string
	Description  string
	Instructions string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	Likes        int64
}

func (q *Queries) GetRecipeList(ctx context.Context) ([]GetRecipeListRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeListRow
	for rows.Next() {
		var i GetRecipeListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Instructions,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeOwner = `-- name: GetRecipeOwner :one
SELECT user_id FROM recipes
WHERE id = $1
`

func (q *Queries) GetRecipeOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getRecipeOwner, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getRecipesFromNilQuery = `-- name: GetRecipesFromNilQuery :many
SELECT recipes.id, recipes.title, recipes.author, recipes.description, recipes.instructions, recipes.image_key, recipes.created_at, recipes.updated_at, recipes.user_id, COUNT(recipe_likes.user_id) AS likes FROM recipes
LEFT JOIN recipe_likes ON recipe_likes.recipe_id = recipes.id
GROUP BY recipes.id
ORDER BY created_at DESC
LIMIT 50
`

type GetRecipesFromNilQueryRow struct {
	ID           uuid.UUID
	Title        string
	Author       string
	Description  string
	Instructions string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	Likes        int64
}

func (q *Queries) GetRecipesFromNilQuery(ctx context.Context) ([]GetRecipesFromNilQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipesFromNilQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipesFromNilQueryRow
	for rows.Next() {
		var i GetRecipesFromNilQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Instructions,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipesFromQuery = `-- name: GetRecipesFromQuery :many
SELECT recipes.id, recipes.title, recipes.author, recipes.description, recipes.instructions, recipes.image_key, recipes.created_at, recipes.updated_at, recipes.user_id, COUNT(recipe_likes.user_id) AS likes FROM recipes
LEFT JOIN recipe_likes ON recipe_likes.recipe_id = recipes.id
WHERE LOWER(title) LIKE '%' || $1::text || '%'
GROUP BY recipes.id
LIMIT 50
`

type GetRecipesFromQueryRow struct {
	ID           uuid.UUID
	Title        string
	Author       string
	Description  string
	Instructions string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	Likes        int64
}

func (q *Queries) GetRecipesFromQuery(ctx context.Context, dollar_1 string) ([]GetRecipesFromQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipesFromQuery, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipesFromQueryRow
	for rows.Next() {
		var i GetRecipesFromQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Instructions,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalRecipes = `-- name: GetTotalRecipes :one
SELECT COUNT(*) FROM recipes
`

func (q *Queries) GetTotalRecipes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalRecipes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsersRecipes = `-- name: GetUsersRecipes :many
SELECT recipes.id, recipes.title, recipes.author, recipes.description, recipes.instructions, recipes.image_key, recipes.created_at, recipes.updated_at, recipes.user_id, COUNT(recipe_likes.user_id) AS likes FROM recipes
INNER JOIN recipe_likes ON recipe_likes.recipe_id = recipes.id
WHERE recipes.user_id = $1
GROUP BY recipes.id
ORDER BY created_at DESC
`

type GetUsersRecipesRow struct {
	ID           uuid.UUID
	Title        string
	Author       string
	Description  string
	Instructions string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	Likes        int64
}

func (q *Queries) GetUsersRecipes(ctx context.Context, userID uuid.UUID) ([]GetUsersRecipesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRecipesRow
	for rows.Next() {
		var i GetUsersRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Instructions,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes SET 
	title = $1,
	description = $2,
	image_key = $3,
	instructions = $4,
	updated_at = NOW()
WHERE id = $5
RETURNING id, title, author, description, instructions, image_key, created_at, updated_at, user_id
`

type UpdateRecipeParams struct {
	Title        string
	Description  string
	ImageKey     string
	Instructions string
	ID           uuid.UUID
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Title,
		arg.Description,
		arg.ImageKey,
		arg.Instructions,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Instructions,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
