// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipeTags.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addRecipeTags = `-- name: AddRecipeTags :exec
INSERT INTO recipe_tags (recipe_id, tag)
SELECT $1, tag
FROM UNNEST($2::text[]) AS tag
ON CONFLICT (recipe_id, tag) DO NOTHING
`

type AddRecipeTagsParams struct {
	RecipeID uuid.UUID
	Tags     []string
}

func (q *Queries) AddRecipeTags(ctx context.Context, arg AddRecipeTagsParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeTags, arg.RecipeID, pq.Array(arg.Tags))
	return err
}

const removeRecipeTag = `-- name: RemoveRecipeTag :exec
DELETE FROM recipe_tags
WHERE recipe_id = $1 AND tag = $2
`

type RemoveRecipeTagParams struct {
	RecipeID uuid.UUID
	Tag      string
}

func (q *Queries) RemoveRecipeTag(ctx context.Context, arg RemoveRecipeTagParams) error {
	_, err := q.db.ExecContext(ctx, removeRecipeTag, arg.RecipeID, arg.Tag)
	return err
}

const resetRecipeTags = `-- name: ResetRecipeTags :exec
DELETE FROM recipe_tags
WHERE recipe_id = $1
`

func (q *Queries) ResetRecipeTags(ctx context.Context, recipeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetRecipeTags, recipeID)
	return err
}
