// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (id, title, author, created_at, updated_at, user_id, description, image_key, instructions)
VALUES(
	gen_random_uuid(),
	$1,
	$2,
	NOW(),
	NOW(),
	$3,
	$4,
	$5,
	$6
)
RETURNING id, title, author, description, image_key, created_at, updated_at, user_id, instructions
`

type CreateRecipeParams struct {
	Title        string
	Author       string
	UserID       uuid.UUID
	Description  string
	ImageKey     string
	Instructions string
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.Title,
		arg.Author,
		arg.UserID,
		arg.Description,
		arg.ImageKey,
		arg.Instructions,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Instructions,
	)
	return i, err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, title, author, description, image_key, created_at, updated_at, user_id, instructions FROM recipes
WHERE id = $1
`

func (q *Queries) GetRecipe(ctx context.Context, id uuid.UUID) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Instructions,
	)
	return i, err
}

const getRecipeList = `-- name: GetRecipeList :many
SELECT id, title, author, description, image_key, created_at, updated_at, user_id, instructions FROM recipes
ORDER BY created_at DESC
LIMIT 10
`

func (q *Queries) GetRecipeList(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Instructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersRecipes = `-- name: GetUsersRecipes :many
SELECT id, title, author, description, image_key, created_at, updated_at, user_id, instructions FROM recipes
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUsersRecipes(ctx context.Context, userID uuid.UUID) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getUsersRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Instructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
