// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, created_at, expires_at, user_id)
VALUES (
	$1,
	NOW(),
	NOW() + interval '30 days',
	$2
) RETURNING id, created_at, revoked_at, expires_at, user_id
`

type CreateRefreshTokenParams struct {
	ID     string
	UserID uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.ID, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT user_id FROM refresh_tokens
WHERE id = $1 AND expires_at > NOW() AND revoked_at IS NULL
`

func (q *Queries) GetRefreshToken(ctx context.Context, id string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, id)
	return err
}
