// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_state.sql

package database

import (
	"context"
)

const getServerState = `-- name: GetServerState :one
SELECT active, message FROM server_state
LIMIT 1
`

func (q *Queries) GetServerState(ctx context.Context) (ServerState, error) {
	row := q.db.QueryRowContext(ctx, getServerState)
	var i ServerState
	err := row.Scan(
		&i.Active,
		&i.Message,
	)
	return i, err
}
