// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_state.sql

package database

import (
	"context"
)

const getServerState = `-- name: GetServerState :one
SELECT active, message FROM server_state
LIMIT 1
`

type GetServerStateRow struct {
	Active  bool
	Message string
}

func (q *Queries) GetServerState(ctx context.Context) (GetServerStateRow, error) {
	row := q.db.QueryRowContext(ctx, getServerState)
	var i GetServerStateRow
	err := row.Scan(&i.Active, &i.Message)
	return i, err
}

const setServerState = `-- name: SetServerState :exec
UPDATE server_state
SET active = $1, message = $2
WHERE id = 1
`

type SetServerStateParams struct {
	Active  bool
	Message string
}

func (q *Queries) SetServerState(ctx context.Context, arg SetServerStateParams) error {
	_, err := q.db.ExecContext(ctx, setServerState, arg.Active, arg.Message)
	return err
}
