// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shoppingListRecipes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRecipeToList = `-- name: AddRecipeToList :exec
INSERT INTO shopping_list_recipes (shopping_list_id, recipe_id, quantity)
VALUES (
	$1,
	$2,
	$3
)
`

type AddRecipeToListParams struct {
	ShoppingListID uuid.UUID
	RecipeID       uuid.UUID
	Quantity       int32
}

func (q *Queries) AddRecipeToList(ctx context.Context, arg AddRecipeToListParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeToList, arg.ShoppingListID, arg.RecipeID, arg.Quantity)
	return err
}

const getRecipesFromList = `-- name: GetRecipesFromList :many
SELECT recipes.id, recipes.title, recipes.author, recipes.description, recipes.image_key, recipes.created_at, recipes.updated_at, recipes.user_id, recipes.instructions, shopping_list_recipes.quantity FROM recipes
INNER JOIN shopping_list_recipes ON shopping_list_recipes.recipe_id = recipes.id
WHERE shopping_list_recipes.shopping_list_id = $1
`

type GetRecipesFromListRow struct {
	ID           uuid.UUID
	Title        string
	Author       string
	Description  string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	Instructions string
	Quantity     int32
}

func (q *Queries) GetRecipesFromList(ctx context.Context, shoppingListID uuid.UUID) ([]GetRecipesFromListRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipesFromList, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipesFromListRow
	for rows.Next() {
		var i GetRecipesFromListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Instructions,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
