// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkRetailConversion = `-- name: CheckRetailConversion :one
SELECT universal_unit, retail_unit FROM retail_conversions
WHERE universal_unit = $1 AND retail_unit = $2
`

type CheckRetailConversionParams struct {
	UniversalUnit string
	RetailUnit    string
}

type CheckRetailConversionRow struct {
	UniversalUnit string
	RetailUnit    string
}

func (q *Queries) CheckRetailConversion(ctx context.Context, arg CheckRetailConversionParams) (CheckRetailConversionRow, error) {
	row := q.db.QueryRowContext(ctx, checkRetailConversion, arg.UniversalUnit, arg.RetailUnit)
	var i CheckRetailConversionRow
	err := row.Scan(&i.UniversalUnit, &i.RetailUnit)
	return i, err
}

const createIngredientRetailUnit = `-- name: CreateIngredientRetailUnit :exec
INSERT INTO ingredient_retail_units (ingredient_id, retail_unit)
VALUES (
	$1,
	$2
)
`

type CreateIngredientRetailUnitParams struct {
	IngredientID uuid.UUID
	RetailUnit   string
}

func (q *Queries) CreateIngredientRetailUnit(ctx context.Context, arg CreateIngredientRetailUnitParams) error {
	_, err := q.db.ExecContext(ctx, createIngredientRetailUnit, arg.IngredientID, arg.RetailUnit)
	return err
}

const createRetailConversion = `-- name: CreateRetailConversion :exec
INSERT INTO retail_conversions (universal_unit, retail_unit, ratio)
VALUES (
	$1,
	$2,
	$3
)
`

type CreateRetailConversionParams struct {
	UniversalUnit string
	RetailUnit    string
	Ratio         float32
}

func (q *Queries) CreateRetailConversion(ctx context.Context, arg CreateRetailConversionParams) error {
	_, err := q.db.ExecContext(ctx, createRetailConversion, arg.UniversalUnit, arg.RetailUnit, arg.Ratio)
	return err
}

const createRetailUnit = `-- name: CreateRetailUnit :exec
INSERT INTO retail_units (name)
VALUES (
	$1
)
`

func (q *Queries) CreateRetailUnit(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createRetailUnit, name)
	return err
}

const createUnit = `-- name: CreateUnit :exec
INSERT INTO units (name, abbreviation)
VALUES (
	$1,
	$2
)
`

type CreateUnitParams struct {
	Name         string
	Abbreviation string
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) error {
	_, err := q.db.ExecContext(ctx, createUnit, arg.Name, arg.Abbreviation)
	return err
}

const createUniversalConversion = `-- name: CreateUniversalConversion :exec
INSERT INTO conversions (ingredient_id, from_unit, to_unit, ratio)
VALUES (
	$1,
	$2,
	$3,
	$4
)
`

type CreateUniversalConversionParams struct {
	IngredientID uuid.UUID
	FromUnit     string
	ToUnit       string
	Ratio        float32
}

func (q *Queries) CreateUniversalConversion(ctx context.Context, arg CreateUniversalConversionParams) error {
	_, err := q.db.ExecContext(ctx, createUniversalConversion,
		arg.IngredientID,
		arg.FromUnit,
		arg.ToUnit,
		arg.Ratio,
	)
	return err
}

const createUniversalUnit = `-- name: CreateUniversalUnit :exec
INSERT INTO universal_units (name)
VALUES(
	$1
)
`

func (q *Queries) CreateUniversalUnit(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createUniversalUnit, name)
	return err
}

const getConversionsByID = `-- name: GetConversionsByID :many
SELECT ingredient_id, from_unit, to_unit, ratio FROM conversions
WHERE ingredient_id = $1
`

func (q *Queries) GetConversionsByID(ctx context.Context, ingredientID uuid.UUID) ([]Conversion, error) {
	rows, err := q.db.QueryContext(ctx, getConversionsByID, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversion
	for rows.Next() {
		var i Conversion
		if err := rows.Scan(
			&i.IngredientID,
			&i.FromUnit,
			&i.ToUnit,
			&i.Ratio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetailConversion = `-- name: GetRetailConversion :many
SELECT universal_unit, retail_unit, ratio FROM retail_conversions
WHERE retail_unit IN (
	SELECT retail_unit FROM ingredient_retail_units
	WHERE ingredient_id = $1)
AND universal_unit = $2
`

type GetRetailConversionParams struct {
	IngredientID  uuid.UUID
	UniversalUnit string
}

func (q *Queries) GetRetailConversion(ctx context.Context, arg GetRetailConversionParams) ([]RetailConversion, error) {
	rows, err := q.db.QueryContext(ctx, getRetailConversion, arg.IngredientID, arg.UniversalUnit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetailConversion
	for rows.Next() {
		var i RetailConversion
		if err := rows.Scan(&i.UniversalUnit, &i.RetailUnit, &i.Ratio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetailUnit = `-- name: GetRetailUnit :one
SELECT name FROM retail_units
WHERE name = $1
`

func (q *Queries) GetRetailUnit(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRetailUnit, name)
	var name_2 string
	err := row.Scan(&name_2)
	return name_2, err
}

const getUnit = `-- name: GetUnit :one
SELECT name FROM units
WHERE name = $1
`

func (q *Queries) GetUnit(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUnit, name)
	var name_2 string
	err := row.Scan(&name_2)
	return name_2, err
}

const getUniversalUnit = `-- name: GetUniversalUnit :one
SELECT name FROM universal_units
WHERE name = $1
`

func (q *Queries) GetUniversalUnit(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUniversalUnit, name)
	var name_2 string
	err := row.Scan(&name_2)
	return name_2, err
}
