// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkAdmin = `-- name: CheckAdmin :one
SELECT admin FROM users
WHERE id = $1
`

func (q *Queries) CheckAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAdmin, id)
	var admin bool
	err := row.Scan(&admin)
	return admin, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_pw, name)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2,
	$3
) RETURNING id, created_at, email, name
`

type CreateUserParams struct {
	Email    string
	HashedPw string
	Name     string
}

type CreateUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Email     string
	Name      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPw, arg.Name)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET deactivated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, id)
	return err
}

const getName = `-- name: GetName :one
SELECT name FROM users
WHERE id = $1
`

func (q *Queries) GetName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getTotalUsers = `-- name: GetTotalUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, email, name, image_key FROM USERS
WHERE id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Name      string
	ImageKey  string
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.ImageKey,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email FROM users
WHERE id = $1
`

func (q *Queries) GetUserEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getUserHash = `-- name: GetUserHash :one
SELECT id, email, name, hashed_pw, image_key, deactivated_at FROM users
WHERE email = $1
`

type GetUserHashRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	HashedPw      string
	ImageKey      string
	DeactivatedAt sql.NullTime
}

func (q *Queries) GetUserHash(ctx context.Context, email string) (GetUserHashRow, error) {
	row := q.db.QueryRowContext(ctx, getUserHash, email)
	var i GetUserHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPw,
		&i.ImageKey,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserImageKey = `-- name: GetUserImageKey :one
SELECT image_key FROM users
WHERE id = $1
`

func (q *Queries) GetUserImageKey(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserImageKey, id)
	var image_key string
	err := row.Scan(&image_key)
	return image_key, err
}

const makeAdmin = `-- name: MakeAdmin :exec
UPDATE users
SET admin = true
WHERE id = $1
`

func (q *Queries) MakeAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, makeAdmin, id)
	return err
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users
SET deactivated_at = NULL
WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, reactivateUser, id)
	return err
}

const reapDeactivatedUsers = `-- name: ReapDeactivatedUsers :execrows
DELETE FROM users
WHERE deactivated_at IS NOT NULL
  AND deactivated_at <= NOW() - INTERVAL '30 days'
`

func (q *Queries) ReapDeactivatedUsers(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapDeactivatedUsers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshUser = `-- name: RefreshUser :one
SELECT id, name, email, image_key FROM users
WHERE id = $1
`

type RefreshUserRow struct {
	ID       uuid.UUID
	Name     string
	Email    string
	ImageKey string
}

func (q *Queries) RefreshUser(ctx context.Context, id uuid.UUID) (RefreshUserRow, error) {
	row := q.db.QueryRowContext(ctx, refreshUser, id)
	var i RefreshUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ImageKey,
	)
	return i, err
}

const setUserImageKey = `-- name: SetUserImageKey :exec
UPDATE users
SET image_key = $2
WHERE id = $1
`

type SetUserImageKeyParams struct {
	ID       uuid.UUID
	ImageKey string
}

func (q *Queries) SetUserImageKey(ctx context.Context, arg SetUserImageKeyParams) error {
	_, err := q.db.ExecContext(ctx, setUserImageKey, arg.ID, arg.ImageKey)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users 
SET hashed_pw = $2, updated_at = NOW()
WHERE email = $1
`

type UpdatePasswordHashParams struct {
	Email    string
	HashedPw string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordHash, arg.Email, arg.HashedPw)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.ID, arg.Name)
	return err
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE users
SET is_verified = TRUE
WHERE email = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, verifyEmail, email)
	return err
}
