// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkAdmin = `-- name: CheckAdmin :one
SELECT admin FROM users
WHERE id = $1
`

func (q *Queries) CheckAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAdmin, id)
	var admin bool
	err := row.Scan(&admin)
	return admin, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_pw, name)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2,
	$3
) RETURNING id, created_at, email, name
`

type CreateUserParams struct {
	Email    string
	HashedPw string
	Name     string
}

type CreateUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Email     string
	Name      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPw, arg.Name)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getName = `-- name: GetName :one
SELECT name FROM users
WHERE id = $1
`

func (q *Queries) GetName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, email, name FROM USERS
WHERE id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Name      string
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getUserHash = `-- name: GetUserHash :one
SELECT id, email, name, hashed_pw FROM users
WHERE email = $1
`

type GetUserHashRow struct {
	ID       uuid.UUID
	Email    string
	Name     string
	HashedPw string
}

func (q *Queries) GetUserHash(ctx context.Context, email string) (GetUserHashRow, error) {
	row := q.db.QueryRowContext(ctx, getUserHash, email)
	var i GetUserHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPw,
	)
	return i, err
}

const makeAdmin = `-- name: MakeAdmin :exec
UPDATE users
SET admin = true
WHERE id = $1
`

func (q *Queries) MakeAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, makeAdmin, id)
	return err
}

const refreshUser = `-- name: RefreshUser :one
SELECT id, name, email FROM users
WHERE id = $1
`

type RefreshUserRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) RefreshUser(ctx context.Context, id uuid.UUID) (RefreshUserRow, error) {
	row := q.db.QueryRowContext(ctx, refreshUser, id)
	var i RefreshUserRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
