// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package database

import (
	"context"
	"time"
)

const createVerification = `-- name: CreateVerification :exec
INSERT INTO verification_tokens (email, token, expires_at)
VALUES (
  $1,
  $2,
  $3
)
`

type CreateVerificationParams struct {
	Email     string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createVerification, arg.Email, arg.Token, arg.ExpiresAt)
	return err
}

const getVerification = `-- name: GetVerification :one
SELECT email, expires_at FROM verification_tokens
WHERE token = $1
`

type GetVerificationRow struct {
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) GetVerification(ctx context.Context, token string) (GetVerificationRow, error) {
	row := q.db.QueryRowContext(ctx, getVerification, token)
	var i GetVerificationRow
	err := row.Scan(&i.Email, &i.ExpiresAt)
	return i, err
}
